# Generated by Django 4.1.7 on 2023-03-26 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('00', 'Танки'), ('01', 'Хилы'), ('02', 'ДД'), ('03', 'Торговцы'), ('04', 'Гилдмастеры'), ('05', 'Квестгиверы'), ('06', 'Кузнецы'), ('07', 'Кожевники0'), ('08', 'Зельевары'), ('09', 'Мастера заклинаний')], max_length=2)),
                ('content', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=200)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
